# Generated by Django 5.1.15 on 2026-06-12 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0002_initial'),
        ('laboratory', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.visit'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='laboratory.labtestrequest'),
        ),
        migrations.AddField(
            model_name='labtestrequestitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laboratory.labtestrequest'),
        ),
        migrations.AddField(
            model_name='samplecollection',
            name='collected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='samplecollection',
            name='request_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sample', to='laboratory.labtestrequestitem'),
        ),
        migrations.AddField(
            model_name='labtestrequestitem',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboratory.testcatalog'),
        ),
        migrations.AddField(
            model_name='testcatalog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='laboratory.testcategory'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testresult',
            name='request_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='laboratory.labtestrequestitem'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
