# Generated by Django 5.1.15 on 2026-06-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestrequest',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('stat', 'STAT (Immediate)')], default='normal', max_length=10),
        ),
    ]
