# Generated by Django 5.1.15 on 2026-06-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalconfig',
            name='name',
            field=models.CharField(default='My Hospital', max_length=255),
        ),
    ]
