# Generated by Django 5.1.15 on 2026-06-12 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantuserindex'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantuserindex',
            new_name='tenants_ten_email_a591ae_idx',
            old_name='tenants_ten_email_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantuserindex',
            new_name='tenants_ten_usernam_da6450_idx',
            old_name='tenants_ten_usernam_idx',
        ),
    ]
