# Generated by Django 5.1.15 on 2026-06-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_subscriptionplan_customization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_patients',
            field=models.PositiveIntegerField(default=1000, help_text='0 = unlimited patients'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_users',
            field=models.PositiveIntegerField(default=10, help_text='0 = unlimited staff'),
        ),
    ]
