# Generated by Django 5.1.15 on 2026-06-12 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0002_initial'),
        ('patients', '0002_initial'),
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispense',
            name='dispensed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispense',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='dispense',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispenses', to='clinical.prescription'),
        ),
        migrations.AddField(
            model_name='dispenseitem',
            name='dispense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.dispense'),
        ),
        migrations.AddField(
            model_name='dispenseitem',
            name='prescription_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.prescriptionitem'),
        ),
        migrations.AddField(
            model_name='dispenseitem',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.drug'),
        ),
        migrations.AddField(
            model_name='drugbatch',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacy.drug'),
        ),
        migrations.AddField(
            model_name='dispenseitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.drugbatch'),
        ),
        migrations.AddField(
            model_name='drug',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.drugcategory'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.drug'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.purchaseorder'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='pharmacy.drugbatch'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='pharmacy.drug'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.supplier'),
        ),
        migrations.AddField(
            model_name='drugbatch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='drugbatch',
            unique_together={('drug', 'batch_number')},
        ),
    ]
